// This file was generated by Gopher Sauce.
// UPDATE IT TO BETTER TEST YOUR CODE.
package types

import (
	"testing"
)

func TestFSCs(t *testing.T) {

}
func TestDex(t *testing.T) {

}
func TestSoftUser(t *testing.T) {

}
func TestUSettings(t *testing.T) {

}
func TestApp(t *testing.T) {

}
func TestTemplateEdits(t *testing.T) {

}
func TestWebRootEdits(t *testing.T) {

}
func TestTEditor(t *testing.T) {

}
func TestNavbars(t *testing.T) {

}
func TestSModal(t *testing.T) {

}
func TestForms(t *testing.T) {

}
func TestSButton(t *testing.T) {

}
func TestSTab(t *testing.T) {

}
func TestDForm(t *testing.T) {

}
func TestAlertbs(t *testing.T) {

}
func TestInputs(t *testing.T) {

}
func TestAput(t *testing.T) {

}
func TestRPut(t *testing.T) {

}
func TestSSWAL(t *testing.T) {

}
func TestSPackageEdit(t *testing.T) {

}
func TestDebugObj(t *testing.T) {

}
func TestDebugNode(t *testing.T) {

}
func TestPkgItem(t *testing.T) {

}
func TestSROC(t *testing.T) {

}
func TestVHuf(t *testing.T) {

}
