// This file was generated by Gopher Sauce.
// UPDATE IT TO BETTER TEST YOUR CODE.
package handlers

import (
	"testing"
	"github.com/cheikhshift/gos/onyx"
)

func TestfApiGet(t *testing.T) {

	h := MakeHandler(Handler)

	req,err := onyx.NewRequest("GET", "/api/get")

	if err != nil {
		panic(err)
	}

	onyx.Handle(req, h, t)
}
