// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDNavPKG = "tmpl/ui/navpkg.tmpl"

//
// Renders HTML of template
// NavPKG with struct types.Dex
func NavPKG(d types.Dex) string {
	return netbNavPKG(d)
}

// Render template with JSON string as
// data.
func netNavPKG(args ...interface{}) string {

	// Get data from JSON
	var d = netcNavPKG(args...)
	return netbNavPKG(d)

}

// template render function
func netbNavPKG(d types.Dex) string {
	localid := templateIDNavPKG
	name := "NavPKG"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcNavPKG(args ...interface{}) (d types.Dex) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
