// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDDelete = "tmpl/ui/user/panel/delete.tmpl"

//
// Renders HTML of template
// Delete with struct types.DForm
func Delete(d types.DForm) string {
	return netbDelete(d)
}

// Render template with JSON string as
// data.
func netDelete(args ...interface{}) string {

	// Get data from JSON
	var d = netcDelete(args...)
	return netbDelete(d)

}

// template render function
func netbDelete(d types.DForm) string {
	localid := templateIDDelete
	name := "Delete"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcDelete(args ...interface{}) (d types.DForm) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
