// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDWebRootEdittwo = "tmpl/ui/user/panel/webtwo.tmpl"

//
// Renders HTML of template
// WebRootEdittwo with struct types.WebRootEdits
func WebRootEdittwo(d types.WebRootEdits) string {
	return netbWebRootEdittwo(d)
}

// Render template with JSON string as
// data.
func netWebRootEdittwo(args ...interface{}) string {

	// Get data from JSON
	var d = netcWebRootEdittwo(args...)
	return netbWebRootEdittwo(d)

}

// template render function
func netbWebRootEdittwo(d types.WebRootEdits) string {
	localid := templateIDWebRootEdittwo
	name := "WebRootEdittwo"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcWebRootEdittwo(args ...interface{}) (d types.WebRootEdits) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
