// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDMethodEditor = "tmpl/editor/methods.tmpl"

//
// Renders HTML of template
// MethodEditor with struct types.VHuf
func MethodEditor(d types.VHuf) string {
	return netbMethodEditor(d)
}

// Render template with JSON string as
// data.
func netMethodEditor(args ...interface{}) string {

	// Get data from JSON
	var d = netcMethodEditor(args...)
	return netbMethodEditor(d)

}

// template render function
func netbMethodEditor(d types.VHuf) string {
	localid := templateIDMethodEditor
	name := "MethodEditor"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcMethodEditor(args ...interface{}) (d types.VHuf) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
