// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDLogin = "tmpl/ui/login.tmpl"

//
// Renders HTML of template
// Login with struct types.Dex
func Login(d types.Dex) string {
	return netbLogin(d)
}

// Render template with JSON string as
// data.
func netLogin(args ...interface{}) string {

	// Get data from JSON
	var d = netcLogin(args...)
	return netbLogin(d)

}

// template render function
func netbLogin(d types.Dex) string {
	localid := templateIDLogin
	name := "Login"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcLogin(args ...interface{}) (d types.Dex) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
