// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDTimerEditor = "tmpl/editor/timers.tmpl"

//
// Renders HTML of template
// TimerEditor with struct types.TEditor
func TimerEditor(d types.TEditor) string {
	return netbTimerEditor(d)
}

// Render template with JSON string as
// data.
func netTimerEditor(args ...interface{}) string {

	// Get data from JSON
	var d = netcTimerEditor(args...)
	return netbTimerEditor(d)

}

// template render function
func netbTimerEditor(d types.TEditor) string {
	localid := templateIDTimerEditor
	name := "TimerEditor"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcTimerEditor(args ...interface{}) (d types.TEditor) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
