// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDObjectEditor = "tmpl/editor/objects.tmpl"

//
// Renders HTML of template
// ObjectEditor with struct types.VHuf
func ObjectEditor(d types.VHuf) string {
	return netbObjectEditor(d)
}

// Render template with JSON string as
// data.
func netObjectEditor(args ...interface{}) string {

	// Get data from JSON
	var d = netcObjectEditor(args...)
	return netbObjectEditor(d)

}

// template render function
func netbObjectEditor(d types.VHuf) string {
	localid := templateIDObjectEditor
	name := "ObjectEditor"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcObjectEditor(args ...interface{}) (d types.VHuf) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
