// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDJS = "tmpl/js.tmpl"

//
// Renders HTML of template
// JS with struct types.Dex
func JS(d types.Dex) string {
	return netbJS(d)
}

// Render template with JSON string as
// data.
func netJS(args ...interface{}) string {

	// Get data from JSON
	var d = netcJS(args...)
	return netbJS(d)

}

// template render function
func netbJS(d types.Dex) string {
	localid := templateIDJS
	name := "JS"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcJS(args ...interface{}) (d types.Dex) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
