// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDTemplateEditTwo = "tmpl/ui/user/panel/tpetwo.tmpl"

//
// Renders HTML of template
// TemplateEditTwo with struct types.TemplateEdits
func TemplateEditTwo(d types.TemplateEdits) string {
	return netbTemplateEditTwo(d)
}

// Render template with JSON string as
// data.
func netTemplateEditTwo(args ...interface{}) string {

	// Get data from JSON
	var d = netcTemplateEditTwo(args...)
	return netbTemplateEditTwo(d)

}

// template render function
func netbTemplateEditTwo(d types.TemplateEdits) string {
	localid := templateIDTemplateEditTwo
	name := "TemplateEditTwo"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcTemplateEditTwo(args ...interface{}) (d types.TemplateEdits) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
