// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDNavPromo = "tmpl/ui/navpromo.tmpl"

//
// Renders HTML of template
// NavPromo with struct types.Dex
func NavPromo(d types.Dex) string {
	return netbNavPromo(d)
}

// Render template with JSON string as
// data.
func netNavPromo(args ...interface{}) string {

	// Get data from JSON
	var d = netcNavPromo(args...)
	return netbNavPromo(d)

}

// template render function
func netbNavPromo(d types.Dex) string {
	localid := templateIDNavPromo
	name := "NavPromo"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcNavPromo(args ...interface{}) (d types.Dex) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
