// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDjButton = "tmpl/ui/user/forms/jbutton.tmpl"

//
// Renders HTML of template
// jButton with struct types.SButton
func JButton(d types.SButton) string {
	return netbjButton(d)
}

// Render template with JSON string as
// data.
func netjButton(args ...interface{}) string {

	// Get data from JSON
	var d = netcjButton(args...)
	return netbjButton(d)

}

// template render function
func netbjButton(d types.SButton) string {
	localid := templateIDjButton
	name := "jButton"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcjButton(args ...interface{}) (d types.SButton) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
