// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDDebuggerNode = "tmpl/ui/debugnode.tmpl"

//
// Renders HTML of template
// DebuggerNode with struct types.DebugObj
func DebuggerNode(d types.DebugObj) string {
	return netbDebuggerNode(d)
}

// Render template with JSON string as
// data.
func netDebuggerNode(args ...interface{}) string {

	// Get data from JSON
	var d = netcDebuggerNode(args...)
	return netbDebuggerNode(d)

}

// template render function
func netbDebuggerNode(d types.DebugObj) string {
	localid := templateIDDebuggerNode
	name := "DebuggerNode"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcDebuggerNode(args ...interface{}) (d types.DebugObj) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
