// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDForm = "tmpl/ui/user/forms/form.tmpl"

//
// Renders HTML of template
// Form with struct types.Forms
func Form(d types.Forms) string {
	return netbForm(d)
}

// Render template with JSON string as
// data.
func netForm(args ...interface{}) string {

	// Get data from JSON
	var d = netcForm(args...)
	return netbForm(d)

}

// template render function
func netbForm(d types.Forms) string {
	localid := templateIDForm
	name := "Form"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcForm(args ...interface{}) (d types.Forms) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
