// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDSWAL = "tmpl/ui/user/forms/swal.tmpl"

//
// Renders HTML of template
// SWAL with struct types.SSWAL
func SWAL(d types.SSWAL) string {
	return netbSWAL(d)
}

// Render template with JSON string as
// data.
func netSWAL(args ...interface{}) string {

	// Get data from JSON
	var d = netcSWAL(args...)
	return netbSWAL(d)

}

// template render function
func netbSWAL(d types.SSWAL) string {
	localid := templateIDSWAL
	name := "SWAL"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcSWAL(args ...interface{}) (d types.SSWAL) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
