// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDEndpointTesting = "tmpl/ui/endpointtester.tmpl"

//
// Renders HTML of template
// EndpointTesting with struct types.Dex
func EndpointTesting(d types.Dex) string {
	return netbEndpointTesting(d)
}

// Render template with JSON string as
// data.
func netEndpointTesting(args ...interface{}) string {

	// Get data from JSON
	var d = netcEndpointTesting(args...)
	return netbEndpointTesting(d)

}

// template render function
func netbEndpointTesting(d types.Dex) string {
	localid := templateIDEndpointTesting
	name := "EndpointTesting"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcEndpointTesting(args ...interface{}) (d types.Dex) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
