// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDRM = "tmpl/ui/user/rm.tmpl"

//
// Renders HTML of template
// RM with struct types.FSCs
func RM(d types.FSCs) string {
	return netbRM(d)
}

// Render template with JSON string as
// data.
func netRM(args ...interface{}) string {

	// Get data from JSON
	var d = netcRM(args...)
	return netbRM(d)

}

// template render function
func netbRM(d types.FSCs) string {
	localid := templateIDRM
	name := "RM"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcRM(args ...interface{}) (d types.FSCs) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
