// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDPackageEdit = "tmpl/ui/user/panel/package.tmpl"

//
// Renders HTML of template
// PackageEdit with struct types.SPackageEdit
func PackageEdit(d types.SPackageEdit) string {
	return netbPackageEdit(d)
}

// Render template with JSON string as
// data.
func netPackageEdit(args ...interface{}) string {

	// Get data from JSON
	var d = netcPackageEdit(args...)
	return netbPackageEdit(d)

}

// template render function
func netbPackageEdit(d types.SPackageEdit) string {
	localid := templateIDPackageEdit
	name := "PackageEdit"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcPackageEdit(args ...interface{}) (d types.SPackageEdit) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
