// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDDebugger = "tmpl/ui/debugger.tmpl"

//
// Renders HTML of template
// Debugger with struct types.DebugObj
func Debugger(d types.DebugObj) string {
	return netbDebugger(d)
}

// Render template with JSON string as
// data.
func netDebugger(args ...interface{}) string {

	// Get data from JSON
	var d = netcDebugger(args...)
	return netbDebugger(d)

}

// template render function
func netbDebugger(d types.DebugObj) string {
	localid := templateIDDebugger
	name := "Debugger"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcDebugger(args ...interface{}) (d types.DebugObj) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
