// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDGroup = "tmpl/ui/user/forms/tab.tmpl"

//
// Renders HTML of template
// Group with struct types.STab
func Group(d types.STab) string {
	return netbGroup(d)
}

// Render template with JSON string as
// data.
func netGroup(args ...interface{}) string {

	// Get data from JSON
	var d = netcGroup(args...)
	return netbGroup(d)

}

// template render function
func netbGroup(d types.STab) string {
	localid := templateIDGroup
	name := "Group"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcGroup(args ...interface{}) (d types.STab) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
