// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDSubmit = "tmpl/ui/submit.tmpl"

//
// Renders HTML of template
// Submit with struct types.Dex
func Submit(d types.Dex) string {
	return netbSubmit(d)
}

// Render template with JSON string as
// data.
func netSubmit(args ...interface{}) string {

	// Get data from JSON
	var d = netcSubmit(args...)
	return netbSubmit(d)

}

// template render function
func netbSubmit(d types.Dex) string {
	localid := templateIDSubmit
	name := "Submit"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcSubmit(args ...interface{}) (d types.Dex) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
