// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDCrashedPage = "tmpl/ui/crashedpage.tmpl"

//
// Renders HTML of template
// CrashedPage with struct types.Dex
func CrashedPage(d types.Dex) string {
	return netbCrashedPage(d)
}

// Render template with JSON string as
// data.
func netCrashedPage(args ...interface{}) string {

	// Get data from JSON
	var d = netcCrashedPage(args...)
	return netbCrashedPage(d)

}

// template render function
func netbCrashedPage(d types.Dex) string {
	localid := templateIDCrashedPage
	name := "CrashedPage"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcCrashedPage(args ...interface{}) (d types.Dex) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
