// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	gosweb "github.com/cheikhshift/gos/web"
)

// Template path
var templateIDPluginList = "tmpl/ui/pluginlist.tmpl"

//
// Renders HTML of template
// PluginList with struct gosweb.NoStruct
func PluginList(d gosweb.NoStruct) string {
	return netbPluginList(d)
}

// Render template with JSON string as
// data.
func netPluginList(args ...interface{}) string {

	// Get data from JSON
	var d = netcPluginList(args...)
	return netbPluginList(d)

}

// template render function
func netbPluginList(d gosweb.NoStruct) string {
	localid := templateIDPluginList
	name := "PluginList"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcPluginList(args ...interface{}) (d gosweb.NoStruct) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
