// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDPUT = "tmpl/ui/user/forms/aput.tmpl"

//
// Renders HTML of template
// PUT with struct types.Aput
func PUT(d types.Aput) string {
	return netbPUT(d)
}

// Render template with JSON string as
// data.
func netPUT(args ...interface{}) string {

	// Get data from JSON
	var d = netcPUT(args...)
	return netbPUT(d)

}

// template render function
func netbPUT(d types.Aput) string {
	localid := templateIDPUT
	name := "PUT"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcPUT(args ...interface{}) (d types.Aput) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
