// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDInput = "tmpl/ui/input.tmpl"

//
// Renders HTML of template
// Input with struct types.Inputs
func Input(d types.Inputs) string {
	return netbInput(d)
}

// Render template with JSON string as
// data.
func netInput(args ...interface{}) string {

	// Get data from JSON
	var d = netcInput(args...)
	return netbInput(d)

}

// template render function
func netbInput(d types.Inputs) string {
	localid := templateIDInput
	name := "Input"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcInput(args ...interface{}) (d types.Inputs) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
