// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDStructEditor = "tmpl/editor/structs.tmpl"

//
// Renders HTML of template
// StructEditor with struct types.VHuf
func StructEditor(d types.VHuf) string {
	return netbStructEditor(d)
}

// Render template with JSON string as
// data.
func netStructEditor(args ...interface{}) string {

	// Get data from JSON
	var d = netcStructEditor(args...)
	return netbStructEditor(d)

}

// template render function
func netbStructEditor(d types.VHuf) string {
	localid := templateIDStructEditor
	name := "StructEditor"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcStructEditor(args ...interface{}) (d types.VHuf) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
