// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDRPUT = "tmpl/ui/user/forms/rput.tmpl"

//
// Renders HTML of template
// RPUT with struct types.RPut
func RPUT(d types.RPut) string {
	return netbRPUT(d)
}

// Render template with JSON string as
// data.
func netRPUT(args ...interface{}) string {

	// Get data from JSON
	var d = netcRPUT(args...)
	return netbRPUT(d)

}

// template render function
func netbRPUT(d types.RPut) string {
	localid := templateIDRPUT
	name := "RPUT"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcRPUT(args ...interface{}) (d types.RPut) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
