// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDNavMain = "tmpl/ui/navmain.tmpl"

//
// Renders HTML of template
// NavMain with struct types.Dex
func NavMain(d types.Dex) string {
	return netbNavMain(d)
}

// Render template with JSON string as
// data.
func netNavMain(args ...interface{}) string {

	// Get data from JSON
	var d = netcNavMain(args...)
	return netbNavMain(d)

}

// template render function
func netbNavMain(d types.Dex) string {
	localid := templateIDNavMain
	name := "NavMain"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcNavMain(args ...interface{}) (d types.Dex) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
