// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDWebRootEdit = "tmpl/ui/user/panel/webrootedit.tmpl"

//
// Renders HTML of template
// WebRootEdit with struct types.WebRootEdits
func WebRootEdit(d types.WebRootEdits) string {
	return netbWebRootEdit(d)
}

// Render template with JSON string as
// data.
func netWebRootEdit(args ...interface{}) string {

	// Get data from JSON
	var d = netcWebRootEdit(args...)
	return netbWebRootEdit(d)

}

// template render function
func netbWebRootEdit(d types.WebRootEdits) string {
	localid := templateIDWebRootEdit
	name := "WebRootEdit"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcWebRootEdit(args ...interface{}) (d types.WebRootEdits) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
