// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDROC = "tmpl/ui/user/panel/roc.tmpl"

//
// Renders HTML of template
// ROC with struct types.SROC
func ROC(d types.SROC) string {
	return netbROC(d)
}

// Render template with JSON string as
// data.
func netROC(args ...interface{}) string {

	// Get data from JSON
	var d = netcROC(args...)
	return netbROC(d)

}

// template render function
func netbROC(d types.SROC) string {
	localid := templateIDROC
	name := "ROC"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcROC(args ...interface{}) (d types.SROC) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
