// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDModal = "tmpl/ui/modal.tmpl"

//
// Renders HTML of template
// Modal with struct types.SModal
func Modal(d types.SModal) string {
	return netbModal(d)
}

// Render template with JSON string as
// data.
func netModal(args ...interface{}) string {

	// Get data from JSON
	var d = netcModal(args...)
	return netbModal(d)

}

// template render function
func netbModal(d types.SModal) string {
	localid := templateIDModal
	name := "Modal"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcModal(args ...interface{}) (d types.SModal) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
