// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDWelcome = "tmpl/ui/welcome.tmpl"

//
// Renders HTML of template
// Welcome with struct types.Dex
func Welcome(d types.Dex) string {
	return netbWelcome(d)
}

// Render template with JSON string as
// data.
func netWelcome(args ...interface{}) string {

	// Get data from JSON
	var d = netcWelcome(args...)
	return netbWelcome(d)

}

// template render function
func netbWelcome(d types.Dex) string {
	localid := templateIDWelcome
	name := "Welcome"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcWelcome(args ...interface{}) (d types.Dex) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
