// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/IDE/types"
)

// Template path
var templateIDCss = "tmpl/css.tmpl"

//
// Renders HTML of template
// Css with struct types.Dex
func Css(d types.Dex) string {
	return netbCss(d)
}

// Render template with JSON string as
// data.
func netCss(args ...interface{}) string {

	// Get data from JSON
	var d = netcCss(args...)
	return netbCss(d)

}

// template render function
func netbCss(d types.Dex) string {
	localid := templateIDCss
	name := "Css"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcCss(args ...interface{}) (d types.Dex) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
