// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"github.com/thestrukture/IDE/types"
	"log"
)

// Template path
var templateIDEndpointEditor = "tmpl/editor/endpoints.tmpl"

//
// Renders HTML of template
// EndpointEditor with struct types.TEditor
func EndpointEditor(d types.TEditor) string {
	return netbEndpointEditor(d)
}

// Render template with JSON string as
// data.
func netEndpointEditor(args ...interface{}) string {

	// Get data from JSON
	var d = netcEndpointEditor(args...)
	return netbEndpointEditor(d)

}

// template render function
func netbEndpointEditor(d types.TEditor) string {
	localid := templateIDEndpointEditor
	name := "EndpointEditor"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcEndpointEditor(args ...interface{}) (d types.TEditor) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
