// This file was generated by Gopher Sauce.
// UPDATE IT TO BETTER TEST YOUR CODE.
package globals

import (
	"testing"
)

func TestWindows(t *testing.T) {

	
}

func TestAutocompletePath(t *testing.T) {

}

func TestUpgrader(t *testing.T) {

	
}

func TestPortCount(t *testing.T) {
	if PortCount != 35000 {
		t.Errorf("Wrong Port Count set, expected %v, go %v", 35000, PortCount)
	}
}

func TestDfd(t *testing.T) {

}
