// File generated by Gopher Sauce
// DO NOT EDIT!!
package globals

import "github.com/gorilla/websocket"

var Windows bool
var AutocompletePath string
var Upgrader = websocket.Upgrader{}
var PortCount = 35000
var Dfd string
